apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    name: pittar-spring-parent
  name: pittar-spring-parent
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/pittar/pittar-spring-parent.git
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      env:
      - name: GIT_SOURCE_URL
        value: https://github.com/pittar/pittar-spring-parent.git
      - name: GIT_SOURCE_REF
        value: master
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5
  triggers: []  